CREATE TABLE IF NOT EXISTS PRICES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    BRAND_ID INTEGER NOT NULL,
    START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
    PRICE_LIST BIGINT NOT NULL,
    PRODUCT_ID VARCHAR(255) NOT NULL,
    PRIORITY INTEGER NOT NULL,
    PRICE DOUBLE NOT NULL,
    CURR VARCHAR(3) NOT NULL);

CREATE INDEX idx_price_lookup ON PRICES(BRAND_ID, PRODUCT_ID, START_DATE DESC, END_DATE DESC);